services:
  mysql:
    image: mysql:8.0
    container_name: mikrops-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mikrops_simple
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - mikrops-network

volumes:
  mysql_data:

networks:
  mikrops-network:
    driver: bridge